
INSERT INTO actividad_economica (codigo,nombre,creado_por,pais) values
('1111', 'Cultivo de cereales excepto arroz y para forrajes', 'admin', 'SV'),
('1112', 'Cultivo de legumbres', 'admin', 'SV'),
('1113', 'Cultivo de semillas oleaginosas', 'admin', 'SV'),
('1114', 'Cultivo de plantas para la preparación de semillas', 'admin', 'SV'),
('1119', 'Cultivo de otros cereales excepto arroz y forrajeros n.c.p.', 'admin', 'SV'),
('1120', 'Cultivo de arroz', 'admin', 'SV'),
('1131', 'Cultivo de raíces y tubérculos', 'admin', 'SV'),
('1132', 'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares', 'admin', 'SV'),
('1133', 'Cultivo hortícola de fruto', 'admin', 'SV'),
('1134', 'Cultivo de hortalizas de hoja y otras hortalizas ncp', 'admin', 'SV'),
('1140', 'Cultivo de caña de azúcar', 'admin', 'SV'),
('1150', 'Cultivo de tabaco', 'admin', 'SV'),
('1161', 'Cultivo de algodón', 'admin', 'SV'),
('1162', 'Cultivo de fibras vegetales excepto algodón', 'admin', 'SV'),
('1191', 'Cultivo de plantas no perennes para la producción de semillas y
flores', 'admin', 'SV'),
('1192', 'Cultivo de cereales y pastos para la alimentación animal', 'admin', 'SV'),
('1199', 'Producción de cultivos no estacionales ncp', 'admin', 'SV'),
('1220', 'Cultivo de frutas tropicales', 'admin', 'SV'),
('1230', 'Cultivo de cítricos', 'admin', 'SV'),
('1240', 'Cultivo de frutas de pepita y hueso', 'admin', 'SV'),
('1251', 'Cultivo de frutas ncp', 'admin', 'SV'),
('1252', 'Cultivo de otros frutos y nueces de árboles y arbustos', 'admin', 'SV'),
('1260', 'Cultivo de frutos oleaginosos', 'admin', 'SV'),
('1271', 'Cultivo de café', 'admin', 'SV'),
('1272', 'Cultivo de plantas para la elaboración de bebidas excepto café', 'admin', 'SV'),
('1281', 'Cultivo de especias y aromáticas', 'admin', 'SV'),
('1282', 'Cultivo de plantas para la obtención de productos medicinales y
farmacéuticos', 'admin', 'SV'),
('1291', 'Cultivo de árboles de hule (caucho) para la obtención de látex', 'admin', 'SV'),
('1292', 'Cultivo de plantas para la obtención de productos químicos y
colorantes', 'admin', 'SV'),
('1299', 'Producción de cultivos perennes ncp', 'admin', 'SV'),
('1300', 'Propagación de plantas', 'admin', 'SV'),
('1301', 'Cultivo de plantas y flores ornamentales', 'admin', 'SV'),
('1410', 'Cría y engorde de ganado bovino', 'admin', 'SV'),
('1420', 'Cría de caballos y otros equinos', 'admin', 'SV'),
('1440', 'Cría de ovejas y cabras', 'admin', 'SV'),
('1450', 'Cría de cerdos', 'admin', 'SV'),
('1460', 'Cría de aves de corral y producción de huevos', 'admin', 'SV'),
('1491', 'Cría de abejas apicultura para la obtención de miel y otros
productos apícolas', 'admin', 'SV'),
('1492', 'Cría de conejos', 'admin', 'SV'),
('1493', 'Cría de iguanas y garrobos', 'admin', 'SV'),
('1494', 'Cría de mariposas y otros insectos', 'admin', 'SV'),
('1499', 'Cría y obtención de productos animales n.c.p.', 'admin', 'SV'),
('1500', 'Cultivo de productos agrícolas en combinación con la cría de
animales', 'admin', 'SV'),
('1611', 'Servicios de maquinaria agrícola', 'admin', 'SV'),
('1612', 'Control de plagas', 'admin', 'SV'),
('1613', 'Servicios de riego', 'admin', 'SV'),
('1614', 'Servicios de contratación de mano de obra para la agricultura', 'admin', 'SV'),
('1619', 'Servicios agrícolas ncp', 'admin', 'SV'),
('1621', 'Actividades para mejorar la reproducción, el crecimiento y el
rendimiento de los animales y sus productos', 'admin', 'SV'),
('1622', 'Servicios de mano de obra pecuaria', 'admin', 'SV'),
('1629', 'Servicios pecuarios ncp', 'admin', 'SV'),
('1631', 'Labores post cosecha de preparación de los productos agrícolas
para su comercialización o para la industria', 'admin', 'SV'),
('1632', 'Servicio de beneficio de café', 'admin', 'SV'),
('1633', 'Servicio de beneficiado de plantas textiles (incluye el beneficiado
cuando este es realizado en la misma explotación agropecuaria)', 'admin', 'SV'),
('1640', 'Tratamiento de semillas para la propagación', 'admin', 'SV'),
('1700', 'Caza ordinaria y mediante trampas, repoblación de animales de
caza y servicios conexos', 'admin', 'SV'),
('2100', 'Silvicultura y otras actividades forestales', 'admin', 'SV'),
('2200', 'Extracción de madera', 'admin', 'SV'),
('2300', 'Recolección de productos diferentes a la madera', 'admin', 'SV'),
('2400', 'Servicios de apoyo a la silvicultura', 'admin', 'SV'),
('3110', 'Pesca marítima de altura y costera', 'admin', 'SV'),
('3120', 'Pesca de agua dulce', 'admin', 'SV'),
('3210', 'Acuicultura marítima', 'admin', 'SV'),
('3220', 'Acuicultura de agua dulce', 'admin', 'SV'),
('3300', 'Servicios de apoyo a la pesca y acuicultura', 'admin', 'SV'),
('5100', 'Extracción de hulla', 'admin', 'SV'),
('5200', 'Extracción y aglomeración de lignito', 'admin', 'SV'),
('6100', 'Extracción de petróleo crudo', 'admin', 'SV'),
('6200', 'Extracción de gas natural', 'admin', 'SV'),
('7100', 'Extracción de minerales de hierro', 'admin', 'SV'),
('7210', 'Extracción de minerales de uranio y torio', 'admin', 'SV'),
('7290', 'Extracción de minerales metalíferos no ferrosos', 'admin', 'SV'),
('8100', 'Extracción de piedra, arena y arcilla', 'admin', 'SV'),
('8910', 'Extracción de minerales para la fabricación de abonos y productos
químicos', 'admin', 'SV'),
('8920', 'Extracción y aglomeración de turba', 'admin', 'SV'),
('8930', 'Extracción de sal', 'admin', 'SV'),
('8990', 'Explotación de otras minas y canteras ncp', 'admin', 'SV'),
('9100', 'Actividades de apoyo a la extracción de petróleo y gas natural', 'admin', 'SV'),
('9900', 'Actividades de apoyo a la explotación de minas y canteras', 'admin', 'SV'),
('10101', 'Servicio de rastros y mataderos de bovinos y porcinos', 'admin', 'SV'),
('10102', 'Matanza y procesamiento de bovinos y porcinos', 'admin', 'SV'),
('10103', 'Matanza y procesamientos de aves de corral', 'admin', 'SV'),
('10104', 'Elaboración y conservación de embutidos y tripas naturales', 'admin', 'SV'),
('10105', 'Servicios de conservación y empaque de carnes', 'admin', 'SV'),
('10106', 'Elaboración y conservación de grasas y aceites animales', 'admin', 'SV'),
('10107', 'Servicios de molienda de carne', 'admin', 'SV'),
('10108', 'Elaboración de productos de carne ncp', 'admin', 'SV'),
('10201', 'Procesamiento y conservación de pescado, crustáceos y moluscos', 'admin', 'SV'),
('10209', 'Fabricación de productos de pescado ncp', 'admin', 'SV'),
('10301', 'Elaboración de jugos de frutas y hortalizasv', 'admin', 'SV'),
('10302', 'Elaboración y envase de jaleas, mermeladas y frutas deshidratadas', 'admin', 'SV'),
('10309', 'Elaboración de productos de frutas y hortalizas n.c.p.', 'admin', 'SV'),
('10401', 'Fabricación de aceites y grasas vegetales y animales comestibles', 'admin', 'SV'),
('10402', 'Fabricación de aceites y grasas vegetales y animales no comestibles', 'admin', 'SV'),
('10409', 'Servicio de maquilado de aceites', 'admin', 'SV'),
('10501', 'Fabricación de productos lácteos excepto sorbetes y quesos
sustitutos', 'admin', 'SV'),
('10502', 'Fabricación de sorbetes y helados', 'admin', 'SV'),
('10503', 'Fabricación de quesos', 'admin', 'SV'),
('10611', 'Molienda de cereales', 'admin', 'SV'),
('10612', 'Elaboración de cereales para el desayuno y similares', 'admin', 'SV'),
('10613', 'Servicios de beneficiado de productos agrícolas ncp (excluye
Beneficio de azúcar rama 1072 y beneficio de café rama 0163)', 'admin', 'SV'),
('10621', 'Fabricación de almidón', 'admin', 'SV'),
('10628', 'Servicio de molienda de maíz húmedo molino para nixtamal', 'admin', 'SV'),
('10711', 'Elaboración de tortillas', 'admin', 'SV'),
('10712', 'Fabricación de pan, galletas y barquillos', 'admin', 'SV'),
('10713', 'Fabricación de repostería', 'admin', 'SV'),
('10721', 'Ingenios azucareros', 'admin', 'SV'),
('10722', 'Molienda de caña de azúcar para la elaboración de dulces', 'admin', 'SV'),
('10723', 'Elaboración de jarabes de azúcar y otros similares', 'admin', 'SV'),
('10724', 'Maquilado de azúcar de caña', 'admin', 'SV'),
('10730', 'Fabricación de cacao, chocolates y productos de confitería', 'admin', 'SV'),
('10740', 'Elaboración de macarrones, fideos, y productos farináceos similares', 'admin', 'SV'),
('10750', 'Elaboración de comidas y platos preparados para la reventa en
locales y/o para exportación', 'admin', 'SV'),
('10791', 'Elaboración de productos de café', 'admin', 'SV'),
('10792', 'Elaboración de especies, sazonadores y condimentos', 'admin', 'SV'),
('10793', 'Elaboración de sopas, cremas y consomé', 'admin', 'SV'),
('10794', 'Fabricación de bocadillos tostados y/o fritos', 'admin', 'SV'),
('10799', 'Elaboración de productos alimenticios ncp', 'admin', 'SV'),
('10800', 'Elaboración de alimentos preparados para animales', 'admin', 'SV'),
('11012', 'Fabricación de aguardiente y licores', 'admin', 'SV'),
('11020', 'Elaboración de vinos', 'admin', 'SV'),
('11030', 'Fabricación de cerveza', 'admin', 'SV'),
('11041', 'Fabricación de aguas gaseosas', 'admin', 'SV'),
('11042', 'Fabricación y envasado de agua', 'admin', 'SV'),
('11043', 'Elaboración de refrescos', 'admin', 'SV'),
('11048', 'Maquilado de aguas gaseosas', 'admin', 'SV'),
('11049', 'Elaboración de bebidas no alcohólicas', 'admin', 'SV'),
('12000', 'Elaboración de productos de tabaco', 'admin', 'SV'),
('13111', 'Preparación de fibras textiles', 'admin', 'SV'),
('13112', 'Fabricación de hilados', 'admin', 'SV'),
('13120', 'Fabricación de telas', 'admin', 'SV'),
('13130', 'Acabado de productos textiles', 'admin', 'SV'),
('13910', 'Fabricación de tejidos de punto y ganchillo', 'admin', 'SV'),
('13921', 'Fabricación de productos textiles para el hogar', 'admin', 'SV'),
('13922', 'Sacos, bolsas y otros artículos textiles', 'admin', 'SV'),
('13929', 'Fabricación de artículos confeccionados con materiales textiles,
excepto prendas de vestir ncp', 'admin', 'SV'),
('13930', 'Fabricación de tapices y alfombras', 'admin', 'SV'),
('13941', 'Fabricación de cuerdas de henequén y otras fibras naturales (lazos,
pitas)', 'admin', 'SV'),
('13942', 'Fabricación de redes de diversos materiales', 'admin', 'SV'),
('13948', 'Maquilado de productos trenzables de cualquier material (petates,
sillas, etc.)', 'admin', 'SV'),
('13991', 'Fabricación de adornos, etiquetas y otros artículos para prendas de
vestir', 'admin', 'SV'),
('13992', 'Servicio de bordados en artículos y prendas de tela', 'admin', 'SV'),
('13999', 'Fabricación de productos textiles ncp', 'admin', 'SV'),
('14101', 'Fabricación de ropa interior, para dormir y similares', 'admin', 'SV'),
('14102', 'Fabricación de ropa para niños', 'admin', 'SV'),
('14103', 'Fabricación de prendas de vestir para ambos sexos', 'admin', 'SV'),
('14104', 'Confección de prendas a medida', 'admin', 'SV'),
('14105', 'Fabricación de prendas de vestir para deportes', 'admin', 'SV'),
('14106', 'Elaboración de artesanías de uso personal confeccionadas
especialmente de materiales textiles', 'admin', 'SV'),
('14108', 'Maquilado de prendas de vestir, accesorios y otros', 'admin', 'SV'),
('14109', 'Fabricación de prendas y accesorios de vestir n.c.p.', 'admin', 'SV'),
('14200', 'Fabricación de artículos de piel', 'admin', 'SV'),
('14301', 'Fabricación de calcetines, calcetas, medias (panty house) y otros
similares', 'admin', 'SV'),
('14302', 'Fabricación de ropa interior de tejido de punto', 'admin', 'SV'),
('14309', 'Fabricación de prendas de vestir de tejido de punto ncp', 'admin', 'SV'),
('15110', 'Curtido y adobo de cueros; adobo y teñido de pieles', 'admin', 'SV'),
('15121', 'Fabricación de maletas, bolsos de mano y otros artículos de
marroquinería', 'admin', 'SV'),
('15122', 'Fabricación de monturas, accesorios y vainas talabartería', 'admin', 'SV'),
('15123', 'Fabricación de artesanías principalmente de cuero natural y
sintético', 'admin', 'SV'),
('15128', 'Maquilado de artículos de cuero natural, sintético y de otros
materiales', 'admin', 'SV'),
('15201', 'Fabricación de calzado', 'admin', 'SV'),
('15202', 'Fabricación de partes y accesorios de calzado', 'admin', 'SV'),
('15208', 'Maquilado de partes y accesorios de calzado', 'admin', 'SV'),
('16100', 'Aserradero y acepilladura de madera', 'admin', 'SV'),
('16210', 'Fabricación de madera laminada, terciada, enchapada y
contrachapada, paneles para la construcción', 'admin', 'SV'),
('16220', 'Fabricación de partes y piezas de carpintería para edificios y
construcciones', 'admin', 'SV'),
('16230', 'Fabricación de envases y recipientes de madera', 'admin', 'SV'),
('16292', 'Fabricación de artesanías de madera, semillas, materiales trenzables', 'admin', 'SV'),
('16299', 'Fabricación de productos de madera, corcho, paja y materiales
trenzables ncp', 'admin', 'SV'),
('17010', 'Fabricación de pasta de madera, papel y cartón', 'admin', 'SV'),
('17020', 'Fabricación de papel y cartón ondulado y envases de papel y cartón', 'admin', 'SV'),
('17091', 'Fabricación de artículos de papel y cartón de uso personal y
doméstico', 'admin', 'SV'),
('17092', 'Fabricación de productos de papel ncp', 'admin', 'SV'),
('18110', 'Impresión', 'admin', 'SV'),
('18120', 'Servicios relacionados con la impresión', 'admin', 'SV'),
('18200', 'Reproducción de grabaciones', 'admin', 'SV'),
('19100', 'Fabricación de productos de hornos de coque', 'admin', 'SV'),
('19201', 'Fabricación de combustible', 'admin', 'SV'),
('19202', 'Fabricación de aceites y lubricantes', 'admin', 'SV'),
('20111', 'Fabricación de materias primas para la fabricación de colorantes', 'admin', 'SV'),
('20112', 'Fabricación de materiales curtientes', 'admin', 'SV'),
('20113', 'Fabricación de gases industriales', 'admin', 'SV'),
('20114', 'Fabricación de alcohol etílico', 'admin', 'SV'),
('20119', 'Fabricación de sustancias químicas básicas', 'admin', 'SV'),
('20120', 'Fabricación de abonos y fertilizantes', 'admin', 'SV'),
('20130', 'Fabricación de plástico y caucho en formas primarias', 'admin', 'SV'),
('20210', 'Fabricación de plaguicidas y otros productos químicos de uso
agropecuario', 'admin', 'SV'),
('20220', 'Fabricación de pinturas, barnices y productos de revestimiento
similares; tintas de imprenta y masillas', 'admin', 'SV'),
('20231', 'Fabricación de jabones, detergentes y similares para limpieza', 'admin', 'SV'),
('20232', 'Fabricación de perfumes, cosméticos y productos de higiene y
cuidado personal, incluyendo tintes, champú, etc.', 'admin', 'SV'),
('20291', 'Fabricación de tintas y colores para escribir y pintar; fabricación de
cintas para impresoras', 'admin', 'SV'),
('20292', 'Fabricación de productos pirotécnicos, explosivos y municiones', 'admin', 'SV'),
('20299', 'Fabricación de productos químicos n.c.p.', 'admin', 'SV'),
('20300', 'Fabricación de fibras artificiales', 'admin', 'SV'),
('21001', 'Manufactura de productos farmacéuticos, sustancias químicas y
productos botánicos', 'admin', 'SV'),
('21008', 'Maquilado de medicamentos', 'admin', 'SV'),
('22110', 'Fabricación de cubiertas y cámaras; renovación y recauchutado de
cubiertas', 'admin', 'SV'),
('22190', 'Fabricación de otros productos de caucho', 'admin', 'SV'),
('22201', 'Fabricación de envases plásticos', 'admin', 'SV'),
('22202', 'Fabricación de productos plásticos para uso personal o doméstico', 'admin', 'SV'),
('22208', 'Maquila de plásticos', 'admin', 'SV'),
('22209', 'Fabricación de productos plásticos n.c.p.', 'admin', 'SV'),
('23101', 'Fabricación de vidrio', 'admin', 'SV'),
('23102', 'Fabricación de recipientes y envases de vidrio', 'admin', 'SV'),
('23108', 'Servicio de maquilado', 'admin', 'SV'),
('23109', 'Fabricación de productos de vidrio ncp', 'admin', 'SV'),
('23910', 'Fabricación de productos refractarios', 'admin', 'SV'),
('23920', 'Fabricación de productos de arcilla para la construcción', 'admin', 'SV'),
('23931', 'Fabricación de productos de cerámica y porcelana no refractaria', 'admin', 'SV'),
('23932', 'Fabricación de productos de cerámica y porcelana ncp', 'admin', 'SV'),
('23940', 'Fabricación de cemento, cal y yeso', 'admin', 'SV'),
('23950', 'Fabricación de artículos de hormigón, cemento y yeso', 'admin', 'SV'),
('23960', 'Corte, tallado y acabado de la piedra', 'admin', 'SV'),
('23990', 'Fabricación de productos minerales no metálicos ncp', 'admin', 'SV'),
('24100', 'Industrias básicas de hierro y acero', 'admin', 'SV'),
('24200', 'Fabricación de productos primarios de metales preciosos y metales
no ferrosos', 'admin', 'SV'),
('24310', 'Fundición de hierro y acero', 'admin', 'SV'),
('24320', 'Fundición de metales no ferrosos', 'admin', 'SV'),
('25111', 'Fabricación de productos metálicos para uso estructural', 'admin', 'SV'),
('25118', 'Servicio de maquila para la fabricación de estructuras metálicas', 'admin', 'SV'),
('25120', 'Fabricación de tanques, depósitos y recipientes de metal', 'admin', 'SV'),
('25130', 'Fabricación de generadores de vapor, excepto calderas de agua
caliente para calefacción central', 'admin', 'SV'),
('25200', 'Fabricación de armas y municiones', 'admin', 'SV'),
('25910', 'Forjado, prensado, estampado y laminado de metales;
pulvimetalurgia', 'admin', 'SV'),
('25920', 'Tratamiento y revestimiento de metales', 'admin', 'SV'),
('25930', 'Fabricación de artículos de cuchillería, herramientas de mano y
artículos de ferretería', 'admin', 'SV'),
('25991', 'Fabricación de envases y artículos conexos de metal', 'admin', 'SV'),
('25992', 'Fabricación de artículos metálicos de uso personal y/o doméstico', 'admin', 'SV'),
('25999', 'Fabricación de productos elaborados de metal ncp', 'admin', 'SV'),
('26100', 'Fabricación de componentes electrónicos', 'admin', 'SV'),
('26200', 'Fabricación de computadoras y equipo conexo', 'admin', 'SV'),
('26300', 'Fabricación de equipo de comunicaciones', 'admin', 'SV'),
('26400', 'Fabricación de aparatos electrónicos de consumo para audio, video
radio y televisión', 'admin', 'SV'),
('26510', 'Fabricación de instrumentos y aparatos para medir, verificar,
ensayar, navegar y de control de procesos industriales', 'admin', 'SV'),
('26520', 'Fabricación de relojes y piezas de relojes', 'admin', 'SV'),
('26600', 'Fabricación de equipo médico de irradiación y equipo electrónico
de uso médico y terapéutico', 'admin', 'SV'),
('26700', 'Fabricación de instrumentos de óptica y equipo fotográfico', 'admin', 'SV'),
('26800', 'Fabricación de medios magnéticos y ópticos', 'admin', 'SV'),
('27100', 'Fabricación de motores, generadores, transformadores eléctricos,
aparatos de distribución y control de electricidad', 'admin', 'SV'),
('27200', 'Fabricación de pilas, baterías y acumuladores', 'admin', 'SV'),
('27310', 'Fabricación de cables de fibra óptica', 'admin', 'SV'),
('27320', 'Fabricación de otros hilos y cables eléctricos', 'admin', 'SV'),
('27330', 'Fabricación de dispositivos de cableados', 'admin', 'SV'),
('27400', 'Fabricación de equipo eléctrico de iluminación', 'admin', 'SV'),
('27500', 'Fabricación de aparatos de uso doméstico', 'admin', 'SV'),
('27900', 'Fabricación de otros tipos de equipo eléctrico', 'admin', 'SV'),
('28110', 'Fabricación de motores y turbinas, excepto motores para
aeronaves, vehículos automotores y motocicletas', 'admin', 'SV'),
('28120', 'Fabricación de equipo hidráulico', 'admin', 'SV'),
('28130', 'Fabricación de otras bombas, compresores, grifos y válvulas', 'admin', 'SV'),
('28140', 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas
de transmisión', 'admin', 'SV'),
('28150', 'Fabricación de hornos y quemadores', 'admin', 'SV'),
('28160', 'Fabricación de equipo de elevación y manipulación', 'admin', 'SV'),
('28170', 'Fabricación de maquinaria y equipo de oficina', 'admin', 'SV'),
('28180', 'Fabricación de herramientas manuales', 'admin', 'SV'),
('28190', 'Fabricación de otros tipos de maquinaria de uso general', 'admin', 'SV'),
('28210', 'Fabricación de maquinaria agropecuaria y forestal', 'admin', 'SV'),
('28220', 'Fabricación de máquinas para conformar metales y maquinaria
herramienta', 'admin', 'SV'),
('28230', 'Fabricación de maquinaria metalúrgica', 'admin', 'SV'),
('28240', 'Fabricación de maquinaria para la explotación de minas y canteras
y para obras de construcción', 'admin', 'SV'),
('28250', 'Fabricación de maquinaria para la elaboración de alimentos,
bebidas y tabaco', 'admin', 'SV'),
('28260', 'Fabricación de maquinaria para la elaboración de productos
textiles, prendas de vestir y cueros', 'admin', 'SV'),
('28291', 'Fabricación de máquinas para imprenta', 'admin', 'SV'),
('28299', 'Fabricación de maquinaria de uso especial ncp', 'admin', 'SV'),
('29100', 'Fabricación vehículos automotores', 'admin', 'SV'),
('29200', 'Fabricación de carrocerías para vehículos automotores; fabricación
de remolques y semiremolques', 'admin', 'SV'),
('29300', 'Fabricación de partes, piezas y accesorios para vehículos
automotores', 'admin', 'SV'),
('30110', 'Fabricación de buques', 'admin', 'SV'),
('30120', 'Construcción y reparación de embarcaciones de recreo', 'admin', 'SV'),
('30200', 'Fabricación de locomotoras y de material rodante', 'admin', 'SV'),
('30300', 'Fabricación de aeronaves y naves espaciales', 'admin', 'SV'),
('30400', 'Fabricación de vehículos militares de combate', 'admin', 'SV'),
('30910', 'Fabricación de motocicletas', 'admin', 'SV'),
('30920', 'Fabricación de bicicletas y sillones de ruedas para inválidos', 'admin', 'SV'),
('30990', 'Fabricación de equipo de transporte ncp', 'admin', 'SV'),
('31001', 'Fabricación de colchones y somier', 'admin', 'SV'),
('31002', 'Fabricación de muebles y otros productos de madera a medida', 'admin', 'SV'),
('31008', 'Servicios de maquilado de muebles', 'admin', 'SV'),
('31009', 'Fabricación de muebles ncp', 'admin', 'SV'),
('32110', 'Fabricación de joyas platerías y joyerías', 'admin', 'SV'),
('32120', 'Fabricación de joyas de imitación (fantasía) y artículos conexos', 'admin', 'SV'),
('32200', 'Fabricación de instrumentos musicales', 'admin', 'SV'),
('32301', 'Fabricación de artículos de deporte', 'admin', 'SV'),
('32308', 'Servicio de maquila de productos deportivos', 'admin', 'SV'),
('32401', 'Fabricación de juegos de mesa y de salón', 'admin', 'SV'),
('32402', 'Servicio de maquilado de juguetes y juegos', 'admin', 'SV'),
('32409', 'Fabricación de juegos y juguetes n.c.p.', 'admin', 'SV'),
('32500', 'Fabricación de instrumentos y materiales médicos y odontológicos', 'admin', 'SV'),
('32901', 'Fabricación de lápices, bolígrafos, sellos y artículos de librería en
general', 'admin', 'SV'),
('32902', 'Fabricación de escobas, cepillos, pinceles y similares', 'admin', 'SV'),
('32903', 'Fabricación de artesanías de materiales diversos', 'admin', 'SV'),
('32904', 'Fabricación de artículos de uso personal y domésticos n.c.p.', 'admin', 'SV'),
('32905', 'Fabricación de accesorios para las confecciones y la marroquinería
n.c.p.', 'admin', 'SV'),
('32908', 'Servicios de maquila ncp', 'admin', 'SV'),
('32909', 'Fabricación de productos manufacturados n.c.p.', 'admin', 'SV'),
('33110', 'Reparación y mantenimiento de productos elaborados de metal', 'admin', 'SV'),
('33120', 'Reparación y mantenimiento de maquinaria', 'admin', 'SV'),
('33130', 'Reparación y mantenimiento de equipo electrónico y óptico', 'admin', 'SV'),
('33140', 'Reparación y mantenimiento de equipo eléctrico', 'admin', 'SV'),
('33150', 'Reparación y mantenimiento de equipo de transporte, excepto
vehículos automotores', 'admin', 'SV'),
('33190', 'Reparación y mantenimiento de equipos n.c.p.', 'admin', 'SV'),
('33200', 'Instalación de maquinaria y equipo industrial', 'admin', 'SV'),
('35101', 'Generación de energía eléctrica', 'admin', 'SV'),
('35102', 'Transmisión de energía eléctrica', 'admin', 'SV'),
('35103', 'Distribución de energía eléctrica', 'admin', 'SV'),
('35200', 'Fabricación de gas, distribución de combustibles gaseosos por
tuberías', 'admin', 'SV'),
('35300', 'Suministro de vapor y agua caliente', 'admin', 'SV'),
('36000', 'Captación, tratamiento y suministro de agua', 'admin', 'SV'),
('37000', 'Evacuación de aguas residuales (alcantarillado)', 'admin', 'SV'),
('38110', 'Recolección y transporte de desechos sólidos proveniente de
hogares y sector urbano', 'admin', 'SV'),
('38120', 'Recolección de desechos peligrosos', 'admin', 'SV'),
('38210', 'Tratamiento y eliminación de desechos inicuos', 'admin', 'SV'),
('38220', 'Tratamiento y eliminación de desechos peligrosos', 'admin', 'SV'),
('38301', 'Reciclaje de desperdicios y desechos textiles', 'admin', 'SV'),
('38302', 'Reciclaje de desperdicios y desechos de plástico y caucho', 'admin', 'SV'),
('38303', 'Reciclaje de desperdicios y desechos de vidrio', 'admin', 'SV'),
('38304', 'Reciclaje de desperdicios y desechos de papel y cartón', 'admin', 'SV'),
('38305', 'Reciclaje de desperdicios y desechos metálicos', 'admin', 'SV'),
('38309', 'Reciclaje de desperdicios y desechos no metálicos n.c.p.', 'admin', 'SV'),
('39000', 'Actividades de Saneamiento y otros Servicios de Gestión de
Desechos', 'admin', 'SV'),
('41001', 'Construcción de edificios residenciales', 'admin', 'SV'),
('41002', 'Construcción de edificios no residenciales', 'admin', 'SV'),
('42100', 'Construcción de carreteras, calles y caminos', 'admin', 'SV'),
('42200', 'Construcción de proyectos de servicio público', 'admin', 'SV'),
('42900', 'Construcción de obras de ingeniería civil n.c.p.', 'admin', 'SV'),
('43110', 'Demolición', 'admin', 'SV'),
('43120', 'Preparación de terreno', 'admin', 'SV'),
('43210', 'Instalaciones eléctricas', 'admin', 'SV'),
('43220', 'Instalación de fontanería, calefacción y aire acondicionado', 'admin', 'SV'),
('43290', 'Otras instalaciones para obras de construcción', 'admin', 'SV'),
('43300', 'Terminación y acabado de edificios', 'admin', 'SV'),
('43900', 'Otras actividades especializadas de construcción', 'admin', 'SV'),
('43901', 'Fabricación de techos y materiales diversos', 'admin', 'SV'),
('45100', 'Venta de vehículos automotores', 'admin', 'SV'),
('45201', 'Reparación mecánica de vehículos automotores', 'admin', 'SV'),
('45202', 'Reparaciones eléctricas del automotor y recarga de baterías', 'admin', 'SV'),
('45203', 'Enderezado y pintura de vehículos automotores', 'admin', 'SV'),
('45204', 'Reparaciones de radiadores, escapes y silenciadores', 'admin', 'SV'),
('45205', 'Reparación y reconstrucción de vías, stop y otros artículos de fibra
de vidrio', 'admin', 'SV'),
('45206', 'Reparación de llantas de vehículos automotores', 'admin', 'SV'),
('45207', 'Polarizado de vehículos (mediante la adhesión de papel especial a
los vidrios)', 'admin', 'SV'),
('45208', 'Lavado y pasteado de vehículos (carwash)', 'admin', 'SV'),
('45209', 'Reparaciones de vehículos n.c.p.', 'admin', 'SV'),
('45211', 'Remolque de vehículos automotores', 'admin', 'SV'),
('45301', 'Venta de partes, piezas y accesorios nuevos para vehículos
automotores', 'admin', 'SV'),
('45302', 'Venta de partes, piezas y accesorios usados para vehículos
automotores', 'admin', 'SV'),
('45401', 'Venta de motocicletas', 'admin', 'SV'),
('45402', 'Venta de repuestos, piezas y accesorios de motocicletas', 'admin', 'SV'),
('45403', 'Mantenimiento y reparación de motocicletas', 'admin', 'SV'),
('46100', 'Venta al por mayor a cambio de retribución o por contrata', 'admin', 'SV'),
('46201', 'Venta al por mayor de materias primas agrícolas', 'admin', 'SV'),
('46202', 'Venta al por mayor de productos de la silvicultura', 'admin', 'SV'),
('46203', 'Venta al por mayor de productos pecuarios y de granja', 'admin', 'SV'),
('46211', 'Venta de productos para uso agropecuario', 'admin', 'SV'),
('46291', 'Venta al por mayor de granos básicos (cereales, leguminosas)', 'admin', 'SV'),
('46292', 'Venta al por mayor de semillas mejoradas para cultivo', 'admin', 'SV'),
('46293', 'Venta al por mayor de café oro y uva', 'admin', 'SV'),
('46294', 'Venta al por mayor de caña de azúcar', 'admin', 'SV'),
('46295', 'Venta al por mayor de flores, plantas y otros productos naturales', 'admin', 'SV'),
('46296', 'Venta al por mayor de productos agrícolas', 'admin', 'SV'),
('46297', 'Venta al por mayor de ganado bovino (vivo)', 'admin', 'SV'),
('46298', 'Venta al por mayor de animales porcinos, ovinos, caprino,
canículas, apícolas, avícolas vivos', 'admin', 'SV'),
('46299', 'Venta de otras especies vivas del reino animal', 'admin', 'SV'),
('46301', 'Venta al por mayor de alimentos', 'admin', 'SV'),
('46302', 'Venta al por mayor de bebidas', 'admin', 'SV'),
('46303', 'Venta al por mayor de tabaco', 'admin', 'SV'),
('46371', 'Venta al por mayor de frutas, hortalizas (verduras), legumbres y
tubérculos', 'admin', 'SV'),
('46372', 'Venta al por mayor de pollos, gallinas destazadas, pavos y otras
aves', 'admin', 'SV'),
('46373', 'Venta al por mayor de carne bovina y porcina, productos de carne y
embutidos', 'admin', 'SV'),
('46374', 'Venta al por mayor de huevos', 'admin', 'SV'),
('46375', 'Venta al por mayor de productos lácteos', 'admin', 'SV'),
('46376', 'Venta al por mayor de productos farináceos de panadería (pan
dulce, cakes, repostería, etc.)', 'admin', 'SV'),
('46377', 'Venta al por mayor de pastas alimenticias, aceites y grasas
comestibles vegetal y animal', 'admin', 'SV'),
('46378', 'Venta al por mayor de sal comestible', 'admin', 'SV'),
('46379', 'Venta al por mayor de azúcar', 'admin', 'SV'),
('46391', 'Venta al por mayor de abarrotes (vinos, licores, productos
alimenticios envasados, etc.)', 'admin', 'SV'),
('46392', 'Venta al por mayor de aguas gaseosas', 'admin', 'SV'),
('46393', 'Venta al por mayor de agua purificada', 'admin', 'SV'),
('46394', 'Venta al por mayor de refrescos y otras bebidas, líquidas o en polvo', 'admin', 'SV'),
('46395', 'Venta al por mayor de cerveza y licores', 'admin', 'SV'),
('46396', 'Venta al por mayor de hielo', 'admin', 'SV'),
('46411', 'Venta al por mayor de hilados, tejidos y productos textiles de
mercería', 'admin', 'SV'),
('46412', 'Venta al por mayor de artículos textiles excepto confecciones para
el hogar', 'admin', 'SV'),
('46413', 'Venta al por mayor de confecciones textiles para el hogar', 'admin', 'SV'),
('46414', 'Venta al por mayor de prendas de vestir y accesorios de vestir', 'admin', 'SV'),
('46415', 'Venta al por mayor de ropa usada', 'admin', 'SV'),
('46416', 'Venta al por mayor de calzado', 'admin', 'SV'),
('46417', 'Venta al por mayor de artículos de marroquinería y talabartería', 'admin', 'SV'),
('46418', 'Venta al por mayor de artículos de peletería', 'admin', 'SV'),
('46419', 'Venta al por mayor de otros artículos textiles n.c.p.', 'admin', 'SV'),
('46471', 'Venta al por mayor de instrumentos musicales', 'admin', 'SV'),
('46472', 'Venta al por mayor de colchones, almohadas, cojines, etc.', 'admin', 'SV'),
('46473', 'Venta al por mayor de artículos de aluminio para el hogar y para
otros usos', 'admin', 'SV'),
('46474', 'Venta al por mayor de depósitos y otros artículos plásticos para el hogar y otros usos, incluyendo los desechables de durapax y no
desechables', 'admin', 'SV'),
('46475', 'Venta al por mayor de cámaras fotográficas, accesorios y materiales', 'admin', 'SV'),
('46482', 'Venta al por mayor de medicamentos, artículos y otros productos
de uso veterinario', 'admin', 'SV'),
('46483', 'Venta al por mayor de productos y artículos de belleza y de uso
personal', 'admin', 'SV'),
('46484', 'Venta de productos farmacéuticos y medicinales', 'admin', 'SV'),
('46491', 'Venta al por mayor de productos medicinales, cosméticos,
perfumería y productos de limpieza', 'admin', 'SV'),
('46492', 'Venta al por mayor de relojes y artículos de joyería', 'admin', 'SV'),
('46493', 'Venta al por mayor de electrodomésticos y artículos del hogar
excepto bazar; artículos de iluminación', 'admin', 'SV'),
('46494', 'Venta al por mayor de artículos de bazar y similares', 'admin', 'SV'),
('46495', 'Venta al por mayor de artículos de óptica', 'admin', 'SV'),
('46496', 'Venta al por mayor de revistas, periódicos, libros, artículos de
librería y artículos de papel y cartón en general', 'admin', 'SV'),
('46497', 'Venta de artículos deportivos, juguetes y rodados', 'admin', 'SV'),
('46498', 'Venta al por mayor de productos usados para el hogar o el uso
personal', 'admin', 'SV'),
('46499', 'Venta al por mayor de enseres domésticos y de uso personal n.c.p.', 'admin', 'SV'),
('46500', 'Venta al por mayor de bicicletas, partes, accesorios y otros', 'admin', 'SV'),
('46510', 'Venta al por mayor de computadoras, equipo periférico y
programas informáticos', 'admin', 'SV'),
('46520', 'Venta al por mayor de equipos de comunicación', 'admin', 'SV'),
('46530', 'Venta al por mayor de maquinaria y equipo agropecuario,
accesorios, partes y suministros', 'admin', 'SV'),
('46590', 'Venta de equipos e instrumentos de uso profesional y científico y
aparatos de medida y control', 'admin', 'SV'),
('46591', 'Venta al por mayor de maquinaria equipo, accesorios y materiales
para la industria de la madera y sus productos', 'admin', 'SV'),
('46592', 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria gráfica y del papel, cartón y productos de papel y
cartón', 'admin', 'SV'),
('46593', 'Venta al por mayor de maquinaria, equipo, accesorios y materiales
para la industria de productos químicos, plástico y caucho', 'admin', 'SV'),
('46594', 'Venta al por mayor de maquinaria, equipo, accesorios y materiales
para la industria metálica y de sus productos', 'admin', 'SV'),
('46595', 'Venta al por mayor de equipamiento para uso médico,
odontológico, veterinario y servicios conexos', 'admin', 'SV'),
('46596', 'Venta al por mayor de maquinaria, equipo, accesorios y partes para
la industria de la alimentación', 'admin', 'SV'),
('46597', 'Venta al por mayor de maquinaria, equipo, accesorios y partes para
la industria textil, confecciones y cuero', 'admin', 'SV'),
('46598', 'Venta al por mayor de maquinaria, equipo y accesorios para la
construcción y explotación de minas y canteras', 'admin', 'SV'),
('46599', 'Venta al por mayor de otro tipo de maquinaria y equipo con sus
accesorios y partes', 'admin', 'SV'),
('46610', 'Venta al por mayor de otros combustibles sólidos, líquidos,
gaseosos y de productos conexos', 'admin', 'SV'),
('46612', 'Venta al por mayor de combustibles para automotores, aviones,
barcos, maquinaria y otros', 'admin', 'SV'),
('46613', 'Venta al por mayor de lubricantes, grasas y otros aceites para
automotores, maquinaria industrial, etc.', 'admin', 'SV'),
('46614', 'Venta al por mayor de gas propano', 'admin', 'SV'),
('46615', 'Venta al por mayor de leña y carbón', 'admin', 'SV'),
('46620', 'Venta al por mayor de metales y minerales metalíferos', 'admin', 'SV'),
('46631', 'Venta al por mayor de puertas, ventanas, vitrinas y similares', 'admin', 'SV'),
('46632', 'Venta al por mayor de artículos de ferretería y pinturerías', 'admin', 'SV'),
('46633', 'Vidrierías', 'admin', 'SV'),
('46634', 'Venta al por mayor de maderas', 'admin', 'SV'),
('46639', 'Venta al por mayor de materiales para la construcción n.c.p.', 'admin', 'SV'),
('46691', 'Venta al por mayor de sal industrial sin yodar', 'admin', 'SV'),
('46692', 'Venta al por mayor de productos intermedios y desechos de origen
textil', 'admin', 'SV'),
('46693', 'Venta al por mayor de productos intermedios y desechos de origen
metálico', 'admin', 'SV'),
('46694', 'Venta al por mayor de productos intermedios y desechos de papel
y cartón', 'admin', 'SV'),

('46695', 'Venta al por mayor fertilizantes, abonos, agroquímicos y productos
similares', 'admin', 'SV'),
('46696', 'Venta al por mayor de productos intermedios y desechos de origen
plástico', 'admin', 'SV'),
('46697', 'Venta al por mayor de tintas para imprenta, productos curtientes y
materias y productos colorantes', 'admin', 'SV'),
('46698', 'Venta de productos intermedios y desechos de origen químico y de
caucho', 'admin', 'SV'),
('46699', 'Venta al por mayor de productos intermedios y desechos ncp', 'admin', 'SV'),
('46701', 'Venta de algodón en oro', 'admin', 'SV'),
('46900', 'Venta al por mayor de otros productos', 'admin', 'SV'),
('46901', 'Venta al por mayor de cohetes y otros productos pirotécnicos', 'admin', 'SV'),
('46902', 'Venta al por mayor de artículos diversos para consumo humano', 'admin', 'SV'),
('46903', 'Venta al por mayor de armas de fuego, municiones y accesorios', 'admin', 'SV'),
('46904', 'Venta al por mayor de toldos y tiendas de campaña de cualquier
material', 'admin', 'SV'),
('46905', 'Venta al por mayor de exhibidores publicitarios y rótulos', 'admin', 'SV'),
('46906', 'Venta al por mayor de artículos promocionales diversos', 'admin', 'SV'),
('47111', 'Venta en supermercados', 'admin', 'SV'),
('47112', 'Venta en tiendas de artículos de primera necesidad', 'admin', 'SV'),
('47119', 'Almacenes (venta de diversos artículos)', 'admin', 'SV'),
('47190', 'Venta al por menor de otros productos en comercios no
especializados', 'admin', 'SV'),
('47199', 'Venta de establecimientos no especializados con surtido
compuesto principalmente de alimentos, bebidas y tabaco', 'admin', 'SV'),
('47211', 'Venta al por menor de frutas y hortalizas', 'admin', 'SV'),
('47212', 'Venta al por menor de carnes, embutidos y productos de granja', 'admin', 'SV'),
('47213', 'Venta al por menor de pescado y mariscos', 'admin', 'SV'),
('47214', 'Venta al por menor de productos lácteos', 'admin', 'SV'),
('47215', 'Venta al por menor de productos de panadería, repostería y galletas', 'admin', 'SV'),
('47216', 'Venta al por menor de huevos', 'admin', 'SV'),
('47217', 'Venta al por menor de carnes y productos cárnicos', 'admin', 'SV'),
('47218', 'Venta al por menor de granos básicos y otros', 'admin', 'SV'),
('47219', 'Venta al por menor de alimentos n.c.p.', 'admin', 'SV'),
('47221', 'Venta al por menor de hielo', 'admin', 'SV'),
('47223', 'Venta de bebidas no alcohólicas, para su consumo fuera del
establecimiento', 'admin', 'SV'),
('47224', 'Venta de bebidas alcohólicas, para su consumo fuera del
establecimiento', 'admin', 'SV'),
('47225', 'Venta de bebidas alcohólicas para su consumo dentro del
establecimiento', 'admin', 'SV'),
('47230', 'Venta al por menor de tabaco', 'admin', 'SV'),
('47300', 'Venta de combustibles, lubricantes y otros (gasolineras)', 'admin', 'SV'),
('47411', 'Venta al por menor de computadoras y equipo periférico', 'admin', 'SV'),
('47412', 'Venta de equipo y accesorios de telecomunicación', 'admin', 'SV'),
('47420', 'Venta al por menor de equipo de audio y video', 'admin', 'SV'),
('47510', 'Venta al por menor de hilados, tejidos y productos textiles de
mercería; confecciones para el hogar y textiles n.c.p.', 'admin', 'SV'),
('47521', 'Venta al por menor de productos de madera', 'admin', 'SV'),
('47522', 'Venta al por menor de artículos de ferretería', 'admin', 'SV'),
('47523', 'Venta al por menor de productos de pinturerías', 'admin', 'SV'),
('47524', 'Venta al por menor en vidrierías', 'admin', 'SV'),
('47529', 'Venta al por menor de materiales de construcción y artículos
conexos', 'admin', 'SV'),
('47530', 'Venta al por menor de tapices, alfombras y revestimientos de
paredes y pisos en comercios especializados', 'admin', 'SV'),
('47591', 'Venta al por menor de muebles', 'admin', 'SV'),
('47592', 'Venta al por menor de artículos de bazar', 'admin', 'SV'),
('47593', 'Venta al por menor de aparatos electrodomésticos, repuestos y
accesorios', 'admin', 'SV'),
('47594', 'Venta al por menor de artículos eléctricos y de iluminación', 'admin', 'SV'),
('47598', 'Venta al por menor de instrumentos musicales', 'admin', 'SV'),
('47610', 'Venta al por menor de libros, periódicos y artículos de papelería en
comercios especializados', 'admin', 'SV'),
('47620', 'Venta al por menor de discos láser, cassettes, cintas de video y
otros', 'admin', 'SV'),
('47630', 'Venta al por menor de productos y equipos de deporte', 'admin', 'SV'),
('47631', 'Venta al por menor de bicicletas, accesorios y repuestos', 'admin', 'SV'),
('47640', 'Venta al por menor de juegos y juguetes en comercios
especializados', 'admin', 'SV'),
('47711', 'Venta al por menor de prendas de vestir y accesorios de vestir', 'admin', 'SV'),
('47712', 'Venta al por menor de calzado', 'admin', 'SV'),
('47713', 'Venta al por menor de artículos de peletería, marroquinería y
talabartería', 'admin', 'SV'),
('47721', 'Venta al por menor de medicamentos farmacéuticos y otros
materiales y artículos de uso médico, odontológico y veterinario', 'admin', 'SV'),
('47722', 'Venta al por menor de productos cosméticos y de tocador', 'admin', 'SV'),
('47731', 'Venta al por menor de productos de joyería, bisutería, óptica,
relojería', 'admin', 'SV'),
('47732', 'Venta al por menor de plantas, semillas, animales y artículos
conexos', 'admin', 'SV'),
('47733', 'Venta al por menor de combustibles de uso doméstico (gas
propano y gas licuado)', 'admin', 'SV'),
('47734', 'Venta al por menor de artesanías, artículos cerámicos y recuerdos
en general', 'admin', 'SV'),
('47735', 'Venta al por menor de ataúdes, lápidas y cruces, trofeos, artículos
religiosos en general', 'admin', 'SV'),
('47736', 'Venta al por menor de armas de fuego, municiones y accesorios', 'admin', 'SV'),
('47737', 'Venta al por menor de artículos de cohetería y pirotécnicos', 'admin', 'SV'),
('47738', 'Venta al por menor de artículos desechables de uso personal y doméstico (servilletas, papel higiénico, pañales, toallas sanitarias,
etc.)', 'admin', 'SV'),
('47739', 'Venta al por menor de otros productos n.c.p.', 'admin', 'SV'),
('47741', 'Venta al por menor de artículos usados', 'admin', 'SV'),
('47742', 'Venta al por menor de textiles y confecciones usados', 'admin', 'SV'),
('47743', 'Venta al por menor de libros, revistas, papel y cartón usados', 'admin', 'SV'),
('47749', 'Venta al por menor de productos usados n.c.p.', 'admin', 'SV'),
('47811', 'Venta al por menor de frutas, verduras y hortalizas', 'admin', 'SV'),
('47814', 'Venta al por menor de productos lácteos', 'admin', 'SV'),
('47815', 'Venta al por menor de productos de panadería, galletas y similares', 'admin', 'SV'),
('47816', 'Venta al por menor de bebidas', 'admin', 'SV'),
('47818', 'Venta al por menor en tiendas de mercado y puestos', 'admin', 'SV'),
('47821', 'Venta al por menor de hilados, tejidos y productos textiles de
mercería en puestos de mercados y ferias', 'admin', 'SV'),
('47822', 'Venta al por menor de artículos textiles excepto confecciones para
el hogar en puestos de mercados y ferias', 'admin', 'SV'),
('47823', 'Venta al por menor de confecciones textiles para el hogar en
puestos de mercados y ferias', 'admin', 'SV'),
('47824', 'Venta al por menor de prendas de vestir, accesorios de vestir y
similares en puestos de mercados y ferias', 'admin', 'SV'),
('47825', 'Venta al por menor de ropa usada', 'admin', 'SV'),
('47826', 'Venta al por menor de calzado, artículos de marroquinería y
talabartería en puestos de mercados y ferias', 'admin', 'SV'),
('47827', 'Venta al por menor de artículos de marroquinería y talabartería en
puestos de mercados y ferias', 'admin', 'SV'),
('47829', 'Venta al por menor de artículos textiles ncp en puestos de
mercados y ferias', 'admin', 'SV'),
('47891', 'Venta al por menor de animales, flores y productos conexos en
puestos de feria y mercados', 'admin', 'SV'),
('47892', 'Venta al por menor de productos medicinales, cosméticos, de
tocador y de limpieza en puestos de ferias y mercados', 'admin', 'SV'),
('47893', 'Venta al por menor de artículos de bazar en puestos de ferias y
mercados', 'admin', 'SV'),
('47894', 'Venta al por menor de artículos de papel, envases, libros, revistas y
conexos en puestos de feria y mercados', 'admin', 'SV'),
('47895', 'Venta al por menor de materiales de construcción, electrodomésticos, accesorios para autos y similares en puestos de
feria y mercados', 'admin', 'SV'),
('47896', 'Venta al por menor de equipos accesorios para las comunicaciones
en puestos de feria y mercados', 'admin', 'SV'),
('47899', 'Venta al por menor en puestos de ferias y mercados n.c.p.', 'admin', 'SV'),
('47910', 'Venta al por menor por correo o Internet', 'admin', 'SV'),
('47990', 'Otros tipos de venta al por menor no realizada, en almacenes,
puestos de venta o mercado', 'admin', 'SV'),
('49110', 'Transporte interurbano de pasajeros por ferrocarril', 'admin', 'SV'),
('49120', 'Transporte de carga por ferrocarril', 'admin', 'SV'),
('49211', 'Transporte de pasajeros urbanos e interurbano mediante buses', 'admin', 'SV'),
('49212', 'Transporte de pasajeros interdepartamental mediante microbuses', 'admin', 'SV'),
('49213', 'Transporte de pasajeros urbanos e interurbano mediante
microbuses', 'admin', 'SV'),
('49214', 'Transporte de pasajeros interdepartamental mediante buses', 'admin', 'SV'),
('49221', 'Transporte internacional de pasajeros', 'admin', 'SV'),
('49222', 'Transporte de pasajeros mediante taxis y autos con chofer', 'admin', 'SV'),
('49223', 'Transporte escolar', 'admin', 'SV'),
('49225', 'Transporte de pasajeros para excursiones', 'admin', 'SV'),
('49226', 'Servicios de transporte de personal', 'admin', 'SV'),
('49229', 'Transporte de pasajeros por vía terrestre ncp', 'admin', 'SV'),
('49231', 'Transporte de carga urbano', 'admin', 'SV'),
('49232', 'Transporte nacional de carga', 'admin', 'SV'),
('49233', 'Transporte de carga internacional', 'admin', 'SV'),
('49234', 'Servicios de mudanza', 'admin', 'SV'),
('49235', 'Alquiler de vehículos de carga con conductor', 'admin', 'SV'),
('49300', 'Transporte por oleoducto o gasoducto', 'admin', 'SV'),
('50110', 'Transporte de pasajeros marítimo y de cabotaje', 'admin', 'SV'),
('50120', 'Transporte de carga marítimo y de cabotaje', 'admin', 'SV'),
('50211', 'Transporte de pasajeros por vías de navegación interiores', 'admin', 'SV'),
('50212', 'Alquiler de equipo de transporte de pasajeros por vías de
navegación interior con conductor', 'admin', 'SV'),
('50220', 'Transporte de carga por vías de navegación interiores', 'admin', 'SV'),

('51100', 'Transporte aéreo de pasajeros', 'admin', 'SV'),
('51201', 'Transporte de carga por vía aérea', 'admin', 'SV'),
('51202', 'Alquiler de equipo de aerotransporte con operadores para el
propósito de transportar carga', 'admin', 'SV'),
('52101', 'Alquiler de instalaciones de almacenamiento en zonas francas', 'admin', 'SV'),
('52102', 'Alquiler de silos para conservación y almacenamiento de granos', 'admin', 'SV'),
('52103', 'Alquiler de instalaciones con refrigeración para almacenamiento y
conservación de alimentos y otros productos', 'admin', 'SV'),
('52109', 'Alquiler de bodegas para almacenamiento y depósito n.c.p.', 'admin', 'SV'),
('52211', 'Servicio de garaje y estacionamiento', 'admin', 'SV'),
('52212', 'Servicios de terminales para el transporte por vía terrestre', 'admin', 'SV'),
('52219', 'Servicios para el transporte por vía terrestre n.c.p.', 'admin', 'SV'),
('52220', 'Servicios para el transporte acuático', 'admin', 'SV'),
('52230', 'Servicios para el transporte aéreo', 'admin', 'SV'),
('52240', 'Manipulación de carga', 'admin', 'SV'),
('52290', 'Servicios para el transporte ncp', 'admin', 'SV'),
('52291', 'Agencias de tramitaciones aduanales', 'admin', 'SV'),
('53100', 'Servicios de correo nacional', 'admin', 'SV'),
('53200', 'Actividades de correo distintas a las actividades postales nacionales', 'admin', 'SV'),
('55101', 'Actividades de alojamiento para estancias cortas', 'admin', 'SV'),
('55102', 'Hoteles', 'admin', 'SV'),
('55200', 'Actividades de campamentos, parques de vehículos de recreo y
parques de caravanas', 'admin', 'SV'),
('55900', 'Alojamiento n.c.p.', 'admin', 'SV'),
('56101', 'Restaurantes', 'admin', 'SV'),
('56106', 'Pupusería', 'admin', 'SV'),
('56107', 'Actividades varias de restaurantes', 'admin', 'SV'),
('56108', 'Comedores', 'admin', 'SV'),
('56109', 'Merenderos ambulantes', 'admin', 'SV'),
('56210', 'Preparación de comida para eventos especiales', 'admin', 'SV'),
('56291', 'Servicios de provisión de comidas por contrato', 'admin', 'SV'),
('56292', 'Servicios de concesión de cafetines y chalet en empresas e
instituciones', 'admin', 'SV'),
('56299', 'Servicios de preparación de comidas ncp', 'admin', 'SV'),
('56301', 'Servicio de expendio de bebidas en salones y bares', 'admin', 'SV'),
('56302', 'Servicio de expendio de bebidas en puestos callejeros, mercados y
ferias', 'admin', 'SV'),
('58110', 'Edición de libros, folletos, partituras y otras ediciones distintas a
estas', 'admin', 'SV'),
('58120', 'Edición de directorios y listas de correos', 'admin', 'SV'),
('58130', 'Edición de periódicos, revistas y otras publicaciones periódicas', 'admin', 'SV'),
('58190', 'Otras actividades de edición', 'admin', 'SV'),
('58200', 'Edición de programas informáticos (software)', 'admin', 'SV'),
('59110', 'Actividades de producción cinematográfica', 'admin', 'SV'),
('59120', 'Actividades de post producción de películas, videos y programas de
televisión', 'admin', 'SV'),
('59130', 'Actividades de distribución de películas cinematográficas, videos y
programas de televisión', 'admin', 'SV'),
('59140', 'Actividades de exhibición de películas cinematográficas y cintas de
vídeo', 'admin', 'SV'),
('59200', 'Actividades de edición y grabación de música', 'admin', 'SV'),
('60100', 'Servicios de difusiones de radio', 'admin', 'SV'),
('60201', 'Actividades de programación y difusión de televisión abierta', 'admin', 'SV'),
('60202', 'Actividades de suscripción y difusión de televisión por cable y/o
suscripción', 'admin', 'SV'),
('60299', 'Servicios de televisión, incluye televisión por cable', 'admin', 'SV'),
('60900', 'Programación y transmisión de radio y televisión', 'admin', 'SV'),
('61101', 'Servicio de telefonía', 'admin', 'SV'),
('61102', 'Servicio de Internet', 'admin', 'SV'),
('61103', 'Servicio de telefonía fija', 'admin', 'SV'),
('61109', 'Servicio de Internet n.c.p.', 'admin', 'SV'),
('61201', 'Servicios de telefonía celular', 'admin', 'SV'),
('61202', 'Servicios de Internet inalámbrico', 'admin', 'SV'),
('61209', 'Servicios de telecomunicaciones inalámbrico n.c.p.', 'admin', 'SV'),
('61301', 'Telecomunicaciones satelitales', 'admin', 'SV'),
('61309', 'Comunicación vía satélite n.c.p.', 'admin', 'SV'),
('61900', 'Actividades de telecomunicación n.c.p.', 'admin', 'SV'),
('62010', 'Programación informática', 'admin', 'SV'),
('62020', 'Consultorías y gestión de servicios informáticos', 'admin', 'SV'),
('62090', 'Otras actividades de tecnología de información y servicios de
computadora', 'admin', 'SV'),
('63110', 'Procesamiento de datos y actividades relacionadas', 'admin', 'SV'),
('63120', 'Portales WEB', 'admin', 'SV'),
('63910', 'Servicios de Agencias de Noticias', 'admin', 'SV'),
('63990', 'Otros servicios de información n.c.p.', 'admin', 'SV'),
('64110', 'Servicios provistos por el Banco Central de El salvador', 'admin', 'SV'),
('64190', 'Bancos', 'admin', 'SV'),
('64192', 'Entidades dedicadas al envío de remesas', 'admin', 'SV'),
('64199', 'Otras entidades financieras', 'admin', 'SV'),
('64200', 'Actividades de sociedades de cartera', 'admin', 'SV'),
('64300', 'Fideicomisos, fondos y otras fuentes de financiamiento', 'admin', 'SV'),
('64910', 'Arrendamientos financieros', 'admin', 'SV'),
('64920', 'Asociaciones cooperativas de ahorro y crédito dedicadas a la
intermediación financiera', 'admin', 'SV'),
('64921', 'Instituciones emisoras de tarjetas de crédito y otros', 'admin', 'SV'),
('64922', 'Tipos de crédito ncp', 'admin', 'SV'),
('64928', 'Prestamistas y casas de empeño', 'admin', 'SV'),
('64990', 'Actividades de servicios financieros, excepto la financiación de
planes de seguros y de pensiones n.c.p.', 'admin', 'SV'),
('65110', 'Planes de seguros de vida', 'admin', 'SV'),
('65120', 'Planes de seguro excepto de vida', 'admin', 'SV'),
('65199', 'Seguros generales de todo tipo', 'admin', 'SV'),
('65200', 'Planes se seguro', 'admin', 'SV'),
('65300', 'Planes de pensiones', 'admin', 'SV'),
('66110', 'Administración de mercados financieros (Bolsa de Valores)', 'admin', 'SV'),
('66120', 'Actividades bursátiles (Corredores de Bolsa)', 'admin', 'SV'),
('66190', 'Actividades auxiliares de la intermediación financiera ncp', 'admin', 'SV'),
('66210', 'Evaluación de riesgos y daños', 'admin', 'SV'),
('66220', 'Actividades de agentes y corredores de seguros', 'admin', 'SV'),
('66290', 'Otras actividades auxiliares de seguros y fondos de pensiones', 'admin', 'SV'),
('66300', 'Actividades de administración de fondos', 'admin', 'SV'),

('68101', 'Servicio de alquiler y venta de lotes en cementerios', 'admin', 'SV'),
('68109', 'Actividades inmobiliarias realizadas con bienes propios o
arrendados n.c.p.', 'admin', 'SV'),
('68200', 'Actividades Inmobiliarias Realizadas a Cambio de una Retribución o
por Contrata', 'admin', 'SV'),
('69100', 'Actividades jurídicas', 'admin', 'SV'),
('69200', 'Actividades de contabilidad, teneduría de libros y auditoría;
asesoramiento en materia de impuestos', 'admin', 'SV'),
('70100', 'Actividades de oficinas centrales de sociedades de cartera', 'admin', 'SV'),
('70200', 'Actividades de consultoría en gestión empresarial', 'admin', 'SV'),
('71101', 'Servicios de arquitectura y planificación urbana y servicios conexos', 'admin', 'SV'),
('71102', 'Servicios de ingeniería', 'admin', 'SV'),
('71103', 'Servicios de agrimensura, topografía, cartografía, prospección y
geofísica y servicios conexos', 'admin', 'SV'),
('71200', 'Ensayos y análisis técnicos', 'admin', 'SV'),
('72100', 'Investigaciones y desarrollo experimental en el campo de las
ciencias naturales y la ingeniería', 'admin', 'SV'),
('72199', 'Investigaciones científicas', 'admin', 'SV'),
('72200', 'Investigaciones y desarrollo experimental en el campo de las
ciencias sociales y las humanidades científica y desarrollo', 'admin', 'SV'),
('73100', 'Publicidad', 'admin', 'SV'),
('73200', 'Investigación de mercados y realización de encuestas de opinión
pública', 'admin', 'SV'),
('74100', 'Actividades de diseño especializado', 'admin', 'SV'),
('74200', 'Actividades de fotografía', 'admin', 'SV'),
('74900', 'Servicios profesionales y científicos ncp', 'admin', 'SV'),
('75000', 'Actividades veterinarias', 'admin', 'SV'),
('77101', 'Alquiler de equipo de transporte terrestre', 'admin', 'SV'),
('77102', 'Alquiler de equipo de transporte acuático', 'admin', 'SV'),
('77103', 'Alquiler de equipo de transporte por vía aérea', 'admin', 'SV'),
('77210', 'Alquiler y arrendamiento de equipo de recreo y deportivo', 'admin', 'SV'),
('77220', 'Alquiler de cintas de video y discos', 'admin', 'SV'),
('77290', 'Alquiler de otros efectos personales y enseres domésticos', 'admin', 'SV'),
('77300', 'Alquiler de maquinaria y equipo', 'admin', 'SV'),
('77400', 'Arrendamiento de productos de propiedad intelectual', 'admin', 'SV'),
('78100', 'Obtención y dotación de personal', 'admin', 'SV'),
('78200', 'Actividades de las agencias de trabajo temporal', 'admin', 'SV'),
('78300', 'Dotación de recursos humanos y gestión; gestión de las funciones
de recursos humanos', 'admin', 'SV'),
('79110', 'Actividades de agencias de viajes y organizadores de viajes;
actividades de asistencia a turistas', 'admin', 'SV'),
('79120', 'Actividades de los operadores turísticos', 'admin', 'SV'),
('79900', 'Otros servicios de reservas y actividades relacionadas', 'admin', 'SV'),

('80100', 'Servicios de seguridad privados', 'admin', 'SV'),
('80201', 'Actividades de servicios de sistemas de seguridad', 'admin', 'SV'),
('80202', 'Actividades para la prestación de sistemas de seguridad', 'admin', 'SV'),
('80300', 'Actividades de investigación', 'admin', 'SV'),
('81100', 'Actividades combinadas de mantenimiento de edificios e
instalaciones', 'admin', 'SV'),
('81210', 'Limpieza general de edificios', 'admin', 'SV'),
('81290', 'Otras actividades combinadas de mantenimiento de edificios e
instalaciones ncp', 'admin', 'SV'),
('81300', 'Servicio de jardinería', 'admin', 'SV'),
('82110', 'Servicios administrativos de oficinas', 'admin', 'SV'),
('82190', 'Servicio de fotocopiado y similares, excepto en imprentas', 'admin', 'SV'),
('82200', 'Actividades de las centrales de llamadas (call center)', 'admin', 'SV'),
('82300', 'Organización de convenciones y ferias de negocios', 'admin', 'SV'),
('82910', 'Actividades de agencias de cobro y oficinas de crédito', 'admin', 'SV'),
('82921', 'Servicios de envase y empaque de productos alimenticios', 'admin', 'SV'),
('82922', 'Servicios de envase y empaque de productos medicinales', 'admin', 'SV'),
('82929', 'Servicio de envase y empaque ncp', 'admin', 'SV'),
('82990', 'Actividades de apoyo empresariales ncp', 'admin', 'SV'),
('84110', 'Actividades de la Administración Pública en general', 'admin', 'SV'),
('84111', 'Alcaldías municipales', 'admin', 'SV'),
('84120', 'Regulación de las actividades de prestación de servicios sanitarios, educativos, culturales y otros servicios sociales, excepto seguridad
social', 'admin', 'SV'),
('84130', 'Regulación y facilitación de la actividad económica', 'admin', 'SV'),
('84210', 'Actividades de administración y funcionamiento del Ministerio de
Relaciones Exteriores', 'admin', 'SV'),
('84220', 'Actividades de defensa', 'admin', 'SV'),
('84230', 'Actividades de mantenimiento del orden público y de seguridad', 'admin', 'SV'),
('84300', 'Actividades de planes de seguridad social de afiliación obligatoria', 'admin', 'SV'),
('85101', 'Guardería educativa', 'admin', 'SV'),
('85102', 'Enseñanza preescolar o parvularia', 'admin', 'SV'),
('85103', 'Enseñanza primaria', 'admin', 'SV'),
('85104', 'Servicio de educación preescolar y primaria integrada', 'admin', 'SV'),
('85211', 'Enseñanza secundaria tercer ciclo (7°, 8° y 9°)', 'admin', 'SV'),
('85212', 'Enseñanza secundaria de formación general bachillerato', 'admin', 'SV'),
('85221', 'Enseñanza secundaria de formación técnica y profesional', 'admin', 'SV'),
('85222', 'Enseñanza secundaria de formación técnica y profesional integrada
con enseñanza primaria', 'admin', 'SV'),
('85301', 'Enseñanza superior universitaria', 'admin', 'SV'),
('85302', 'Enseñanza superior no universitaria', 'admin', 'SV'),
('85303', 'Enseñanza superior integrada a educación secundaria y/o primaria', 'admin', 'SV'),
('85410', 'Educación deportiva y recreativa', 'admin', 'SV'),
('85420', 'Educación cultural', 'admin', 'SV'),
('85490', 'Otros tipos de enseñanza n.c.p.', 'admin', 'SV'),
('85499', 'Enseñanza formal', 'admin', 'SV'),
('85500', 'Servicios de apoyo a la enseñanza', 'admin', 'SV'),
('86100', 'Actividades de hospitales', 'admin', 'SV'),
('86201', 'Clínicas médicas', 'admin', 'SV'),
('86202', 'Servicios de Odontología', 'admin', 'SV'),
('86203', 'Servicios médicos', 'admin', 'SV'),
('86901', 'Servicios de análisis y estudios de diagnóstico', 'admin', 'SV'),
('86902', 'Actividades de atención de la salud humana', 'admin', 'SV'),
('86909', 'Otros Servicio relacionados con la salud ncp', 'admin', 'SV'),
('87100', 'Residencias de ancianos con atención de enfermería', 'admin', 'SV'),
('87200', 'Instituciones dedicadas al tratamiento del retraso mental,
problemas de salud mental y el uso indebido de sustancias nocivas', 'admin', 'SV'),
('87300', 'Instituciones dedicadas al cuidado de ancianos y discapacitados', 'admin', 'SV'),
('87900', 'Actividades de asistencia a niños y jóvenes', 'admin', 'SV'),
('87901', 'Otras actividades de atención en instituciones', 'admin', 'SV'),
('88100', 'Actividades de asistencia sociales sin alojamiento para ancianos y
discapacitados', 'admin', 'SV'),
('88900', 'Servicios sociales sin alojamiento ncp', 'admin', 'SV'),
('90000', 'Actividades creativas artísticas y de esparcimiento', 'admin', 'SV'),
('91010', 'Actividades de bibliotecas y archivos', 'admin', 'SV'),
('91020', 'Actividades de museos y preservación de lugares y edificios
históricos', 'admin', 'SV'),
('91030', 'Actividades de jardines botánicos, zoológicos y de reservas
naturales', 'admin', 'SV'),
('92000', 'Actividades de juegos y apuestas', 'admin', 'SV'),
('93110', 'Gestión de instalaciones deportivas', 'admin', 'SV'),
('93120', 'Actividades de clubes deportivos', 'admin', 'SV'),
('93190', 'Otras actividades deportivas', 'admin', 'SV'),
('93210', 'Actividades de parques de atracciones y parques temáticos', 'admin', 'SV'),
('93291', 'Discotecas y salas de baile', 'admin', 'SV'),
('93298', 'Centros vacacionales', 'admin', 'SV'),
('93299', 'Actividades de esparcimiento ncp', 'admin', 'SV'),
('94110', 'Actividades de organizaciones empresariales y de empleadores', 'admin', 'SV'),
('94120', 'Actividades de organizaciones profesionales', 'admin', 'SV'),
('94200', 'Actividades de sindicatos', 'admin', 'SV'),
('94910', 'Actividades de organizaciones religiosas', 'admin', 'SV'),
('94920', 'Actividades de organizaciones políticas', 'admin', 'SV'),
('94990', 'Actividades de asociaciones n.c.p.', 'admin', 'SV'),
('95110', 'Reparación de computadoras y equipo periférico', 'admin', 'SV'),
('95120', 'Reparación de equipo de comunicación', 'admin', 'SV'),
('95210', 'Reparación de aparatos electrónicos de consumo', 'admin', 'SV'),
('95220', 'Reparación de aparatos doméstico y equipo de hogar y jardín', 'admin', 'SV'),
('95230', 'Reparación de calzado y artículos de cuero', 'admin', 'SV'),
('95240', 'Reparación de muebles y accesorios para el hogar', 'admin', 'SV'),
('95291', 'Reparación de Instrumentos musicales', 'admin', 'SV'),
('95292', 'Servicios de cerrajería y copiado de llaves', 'admin', 'SV'),
('95293', 'Reparación de joyas y relojes', 'admin', 'SV'),
('95294', 'Reparación de bicicletas, sillas de ruedas y rodados n.c.p.', 'admin', 'SV'),
('95299', 'Reparaciones de enseres personales n.c.p.', 'admin', 'SV'),
('96010', 'Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco', 'admin', 'SV'),
('96020', 'Peluquería y otros tratamientos de belleza', 'admin', 'SV'),
('96030', 'Pompas fúnebres y actividades conexas', 'admin', 'SV'),
('96091', 'Servicios de sauna y otros servicios para la estética corporal n.c.p.', 'admin', 'SV'),
('97000', 'Actividad de los hogares en calidad de empleadores de personal doméstico', 'admin', 'SV'),
('98100', 'Actividades indiferenciadas de producción de bienes de los hogares privados para uso propio', 'admin', 'SV'),
('98200', 'Actividades indiferenciadas de producción de servicios de los hogares privados para uso propio', 'admin', 'SV'),
('99000', 'Actividades de organizaciones y órganos extraterritoriales', 'admin', 'SV'),
('10001', 'Empleados', 'admin', 'SV'),
('10002', 'Jubilado', 'admin', 'SV'),
('10003', 'Estudiante', 'admin', 'SV'),
('10004', 'Desempleado', 'admin', 'SV'),
('10005', 'Otros', 'admin', 'SV');