-- This is an empty migration.
INSERT INTO pais (CODIGO, NOMBRE, creado_por)
VALUES
    ('9300', 'EL SALVADOR', 'admin');

INSERT INTO departamento (codigo, nombre, creado_por)
VALUES
    ('01', 'Ahuachapán', 'admin'),
    ('02', 'Santa Ana', 'admin'),
    ('03', 'Sonsonate', 'admin'),
    ('04', 'Chalatenango', 'admin'),
    ('05', 'La Libertad', 'admin'),
    ('06', 'San Salvador', 'admin'),
    ('07', 'Cuscatlán', 'admin'),
    ('08', 'La Paz', 'admin'),
    ('09', 'Cabañas', 'admin'),
    ('10', 'San Vicente', 'admin'),
    ('11', 'Usulután', 'admin'),
    ('12', 'San Miguel', 'admin'),
    ('13', 'Morazán', 'admin'),
    ('14', 'La Unión', 'admin');
    
INSERT INTO municipio (codigo, nombre, codigo_departamento, creado_por)
VALUES
  
    ('01', 'Ahuachapán', '01', 'admin'),
    ('02', 'Apaneca', '01', 'admin'),
    ('03', 'Atiquizaya', '01', 'admin'),
    ('04', 'Concepción de Ataco', '01', 'admin'),
    ('05', 'El Refugio', '01', 'admin'),
    ('06', 'Guaymango', '01', 'admin'),
    ('07', 'Jujutla', '01', 'admin'),
    ('08', 'San Francisco Menéndez', '01', 'admin'),
    ('09', 'San Lorenzo', '01', 'admin'),
    ('10', 'San Pedro Puxtla', '01', 'admin'),
    ('11', 'Tacuba', '01', 'admin'),
    ('12', 'Turín', '01', 'admin'),
    ('01', 'Candelaria de la Frontera', '02', 'admin'),
    ('02', 'Coatepeque', '02', 'admin'),
    ('03', 'Chalchuapa', '02', 'admin'),
    ('04', 'El Congo', '02', 'admin'),
    ('05', 'El Porvenir', '02', 'admin'),
    ('06', 'Masahuat', '02', 'admin'),
    ('07', 'Metapán', '02', 'admin'),
    ('08', 'San Antonio Pajonal', '02', 'admin'),
    ('09', 'San Sebastián Salitrillo', '02', 'admin'),
    ('10', 'Santa Ana', '02', 'admin'),
    ('11', 'Santa Rosa Guachipilín', '02', 'admin'),
    ('12', 'Santiago de la Frontera', '02', 'admin'),
    ('13', 'Texistepeque', '02', 'admin'),
    ('01', 'Acajutla', '03', 'admin'),
    ('02', 'Armenia', '03', 'admin'),
    ('03', 'Caluco', '03', 'admin'),
    ('04', 'Cuisnahuat', '03', 'admin'),
    ('05', 'Santa Isabel Ishuatán', '03', 'admin'),
    ('06', 'Izalco', '03', 'admin'),
    ('07', 'Juayúa', '03', 'admin'),
    ('08', 'Nahuizalco', '03', 'admin'),
    ('09', 'Nahulingo', '03', 'admin'),
    ('10', 'Salcoatitán', '03', 'admin'),
    ('11', 'San Antonio del Monte', '03', 'admin'),
    ('12', 'San Julián', '03', 'admin'),
    ('13', 'Santa Catarina Masahuat', '03', 'admin'),  
    ('14', 'Santo Domingo Guzmán', '03', 'admin'),
    ('15', 'Sonsonate', '03', 'admin'),
    ('16', 'Sonzacate', '03', 'admin'),
    ('01', 'Agua Caliente', '04', 'admin'),
    ('02', 'Arcatao', '04', 'admin'),
    ('03', 'Azacualpa', '04', 'admin'),
    ('04', 'Citalá', '04', 'admin'),
    ('05', 'Comalapa', '04', 'admin'),
    ('06', 'Concepción Quezaltepeque', '04', 'admin'),
    ('07', 'Chalatenango', '04', 'admin'),
    ('08', 'Dulce Nombre de María', '04', 'admin'),
    ('09', 'El Carrizal', '04', 'admin'),
    ('10', 'El Paraíso', '04', 'admin'),
    ('11', 'La Laguna', '04', 'admin'),
    ('12', 'La Palma', '04', 'admin'),
    ('13', 'La Reina', '04', 'admin'),
    ('14', 'Las Vueltas', '04', 'admin'),
    ('15', 'Nombre de Jesús', '04', 'admin'),
    ('16', 'Nueva Concepción', '04', 'admin'),
    ('17', 'Nueva Trinidad', '04', 'admin'),
    ('18', 'Ojos de Agua', '04', 'admin'),
    ('19', 'Potonico', '04', 'admin'),
    ('20', 'San Antonio La Cruz', '04', 'admin'),
    ('21', 'San Antonio Ranchos', '04', 'admin'),
    ('22', 'San Fernando', '04', 'admin'),
    ('23', 'San Francisco Lempa', '04', 'admin'),
    ('24', 'San Francisco Morazán', '04', 'admin'),
    ('25', 'San Ignacio', '04', 'admin'),
    ('26', 'San José del Labrador', '04', 'admin'),
    ('27', 'San Juan Cancasque', '04', 'admin'),
    ('28', 'San José Flores', '04', 'admin'),
    ('29', 'San Luis del Carmen', '04', 'admin'),
    ('30', 'San Miguel Mercedes', '04', 'admin'),
    ('31', 'San Rafael', '04', 'admin'),
    ('32', 'Santa Rita', '04', 'admin'),
    ('33', 'Tejutla', '04', 'admin'),
    ('01', 'Antiguo Cuscatlán', '05', 'admin'),
    ('02', 'Ciudad Arce', '05', 'admin'),
    ('03', 'Colón', '05', 'admin'),
    ('04', 'Comasagua', '05', 'admin'),
    ('05', 'Chiltiupán', '05', 'admin'),
    ('06', 'Huizúcar', '05', 'admin'),
    ('07', 'Jayaque', '05', 'admin'),
    ('08', 'Jicalapa', '05', 'admin'),
    ('09', 'La Libertad', '05', 'admin'),
    ('10', 'Nuevo Cuscatlán', '05', 'admin'),
    ('11', 'Santa Tecla', '05', 'admin'),
    ('12', 'Quezaltepeque', '05', 'admin'),
    ('13', 'Sacacoyo', '05', 'admin'),
    ('14', 'San Juan Villanueva', '05', 'admin'),
    ('15', 'San Juan Opico', '05', 'admin'),
    ('16', 'San Matías', '05', 'admin'),
    ('17', 'San Pedro Tacachico', '05', 'admin'),
    ('18', 'Tamanique', '05', 'admin'),
    ('19', 'Talnique', '05', 'admin'),
    ('20', 'Teotepeque', '05', 'admin'),
    ('21', 'Tepecoyo', '05', 'admin'),
    ('22', 'Zaragoza', '05', 'admin'),
    ('01', 'Aguilares', '06', 'admin'),
    ('02', 'Apopa', '06', 'admin'),
    ('03', 'Ayutuxtepeque', '06', 'admin'),
    ('04', 'Cuscatancingo', '06', 'admin'),
    ('05', 'El Paisnal', '06', 'admin'),
    ('06', 'Guazapa', '06', 'admin'),
    ('07', 'Ilopango', '06', 'admin'),
    ('08', 'Mejicanos', '06', 'admin'),
    ('09', 'Nejapa', '06', 'admin'),
    ('10', 'Panchimalco', '06', 'admin'),
    ('11', 'Rosario de Mora', '06', 'admin'),
    ('12', 'San Marcos', '06', 'admin'),
    ('13', 'San Martin', '06', 'admin'),
    ('14', 'San Salvador', '06', 'admin'),
    ('15', 'Santiago Texacuangos', '06', 'admin'),
    ('16', 'Santo Tomás', '06', 'admin'),
    ('17', 'Soyapango', '06', 'admin'),
    ('18', 'Tonacatepeque', '06', 'admin'),
    ('19', 'Ciudad Delgado', '06', 'admin'),
    ('01', 'Candelaria', '07', 'admin'),
     ('02', 'Cojutepeque', '07', 'admin'),
    ('03', 'El Carmen', '07', 'admin'),
    ('04', 'El Rosario', '07', 'admin'),
    ('05', 'Monte San Juan', '07', 'admin'),
    ('06', 'Oratorio de Concepción', '07', 'admin'),
    ('07', 'San Bartolo Perulapía', '07', 'admin'),
    ('08', 'San Cristóbal', '07', 'admin'),
    ('09', 'San José Guayabal', '07', 'admin'),
    ('10', 'San Pedro Perulapán', '07', 'admin'),
    ('11', 'San Rafael Cedros', '07', 'admin'),
    ('12', 'San Ramón', '07', 'admin'),
    ('13', 'Santa Cruz Analquito', '07', 'admin'),
    ('14', 'Santa Cruz Michapa', '07', 'admin'),
    ('15', 'Suchitoto', '07', 'admin'),
    ('16', 'Tenancingo', '07', 'admin'),
    ('01', 'Cuyultitán', '08', 'admin'),
    ('02', 'El Rosario', '08', 'admin'),
    ('03', 'Jerusalén', '08', 'admin'),
    ('04', 'Merced La Ceiba', '08', 'admin'),
    ('05', 'Olocuilta', '08', 'admin'),
    ('06', 'Paraíso de Osorio', '08', 'admin'),
    ('07', 'San Antonio Masahuat', '08', 'admin'),
    ('08', 'San Emigdio', '08', 'admin'),
    ('09', 'San Francisco Chinameca', '08', 'admin'),
    ('10', 'San Juan Nonualco', '08', 'admin'),
    ('11', 'San Juan Talpa', '08', 'admin'),
    ('12', 'San Juan Tepezontes', '08', 'admin'),
    ('13', 'San Luis Talpa', '08', 'admin'),
    ('14', 'San Miguel Tepezontes', '08', 'admin'),
    ('15', 'San Pedro Masahuat', '08', 'admin'),
    ('16', 'San Pedro Nonualco', '08', 'admin'),
    ('17', 'San Rafael Obrajuelo', '08', 'admin'),
    ('18', 'Santa María Ostuma', '08', 'admin'),
    ('19', 'Santiago Nonualco', '08', 'admin'),
    ('20', 'Tapalhuaca', '08', 'admin'),
    ('21', 'Zacatecoluca', '08', 'admin'),
    ('22', 'San Luis La Herradura', '08', 'admin'),
    ('01', 'Cinquera', '09', 'admin'),
    ('02', 'Guacotecti', '09', 'admin'),
    ('03', 'Ilobasco', '09', 'admin'),
    ('04', 'Jutiapa', '09', 'admin'),
    ('05', 'San Isidro', '09', 'admin'),
    ('06', 'Sensuntepeque', '09', 'admin'),
    ('07', 'Tejutepeque', '09', 'admin'),
    ('08', 'Victoria', '09', 'admin'),
    ('09', 'Dolores', '09', 'admin'),
    ('01', 'Apastepeque', '10', 'admin'),
    ('02', 'Guadalupe', '10', 'admin'),
    ('03', 'San Cayetano Istepeque', '10', 'admin'),
    ('04', 'Santa Clara', '10', 'admin'),
    ('05', 'Santo Domingo', '10', 'admin'),
    ('06', 'Santa Catarina Masahuat', '10', 'admin'),
    ('07', 'San Ildefonso', '10', 'admin'),
    ('08', 'San Lorenzo', '10', 'admin'),
    ('09', 'San Sebastián', '10', 'admin'),
    ('10', 'San Vicente', '10', 'admin'),
    ('11', 'Tecoluca', '10', 'admin'),
    ('12', 'Tepetitán', '10', 'admin'),
    ('13', 'Verapaz', '10', 'admin'),
    ('01', 'Alegría', '11', 'admin'),
    ('02', 'Berlín', '11', 'admin'),
    ('03', 'California', '11', 'admin'),
    ('04', 'Concepción Batres', '11', 'admin'),
    ('05', 'El Triunfo', '11', 'admin'),
    ('06', 'Ereguayquín', '11', 'admin'),
    ('07', 'Estanzuelas', '11', 'admin'),
    ('08', 'Jiquilisco', '11', 'admin'),
    ('09', 'Jucuapa', '11', 'admin'),
    ('10', 'Jucuarán', '11', 'admin'),
    ('11', 'Mercedes Umaña', '11', 'admin'),
    ('12', 'Nueva Granada', '11', 'admin'),
    ('13', 'Ozatlán', '11', 'admin'),
    ('14', 'Puerto El Triunfo', '11', 'admin'),
    ('15', 'San Agustín', '11', 'admin'),
    ('16', 'San Buenaventura', '11', 'admin'),
    ('17', 'San Dionisio', '11', 'admin'),
    ('18', 'Santa Elena', '11', 'admin'),
    ('19', 'San Francisco Javier', '11', 'admin'),
    ('20', 'Santa María', '11', 'admin'),
    ('21', 'Santiago de María', '11', 'admin'),
    ('22', 'Tecapán', '11', 'admin'),
    ('23', 'Usulután', '11', 'admin'),
    ('01', 'Carolina', '12', 'admin'),
    ('02', 'Ciudad Barrios', '12', 'admin'),
    ('03', 'Comacarán', '12', 'admin'),
    ('04', 'Chapeltique', '12', 'admin'),
    ('05', 'Chinameca', '12', 'admin'),
    ('06', 'Chirilagua', '12', 'admin'),
    ('07', 'El Transito', '12', 'admin'),
    ('08', 'Lolotique', '12', 'admin'),
    ('09', 'Moncagua', '12', 'admin'),
    ('10', 'Nueva Guadalupe', '12', 'admin'),
    ('11', 'Nuevo Edén de San Juan', '12', 'admin'),
    ('12', 'Quelepa', '12', 'admin'),
    ('13', 'San Antonio del Mosco', '12', 'admin'),
    ('14', 'San Gerardo', '12', 'admin'),
    ('15', 'San Jorge', '12', 'admin'),
    ('16', 'San Luis de la Reina', '12', 'admin'),
    ('17', 'San Miguel', '12', 'admin'),
    ('18', 'San Rafael Oriente', '12', 'admin'),
    ('19', 'Sesori', '12', 'admin'),
    ('20', 'Uluazapa', '12', 'admin'),
    ('01', 'Arambala', '13', 'admin'),
    ('02', 'Cacaopera', '13', 'admin'),
    ('03', 'Corinto', '13', 'admin'),
    ('04', 'Chilanga', '13', 'admin'),
    ('05', 'Delicias de Concepción', '13', 'admin'),
    ('06', 'El Divisadero', '13', 'admin'),
    ('07', 'El Rosario', '13', 'admin'),
    ('08', 'Gualococti', '13', 'admin'),
    ('09', 'Guatajiagua', '13', 'admin'),
    ('10', 'Joateca', '13', 'admin'),
    ('11', 'Jocoaitique', '13', 'admin'),
    ('12', 'Jocoro', '13', 'admin'),
    ('13', 'Lolotiquillo', '13', 'admin'),
    ('14', 'Meanguera', '13', 'admin'),
    ('15', 'Osicala', '13', 'admin'),
     ('16', 'Perquín', '13', 'admin'),
    ('17', 'San Carlos', '13', 'admin'),
    ('18', 'San Fernando', '13', 'admin'), 
    ('19', 'San Francisco Gotera', '13', 'admin'),
    ('20', 'San Isidro', '13', 'admin'),
    ('21', 'San Simón', '13', 'admin'),
    ('22', 'Sensembra', '13', 'admin'),
    ('23', 'Sociedad', '13', 'admin'),
    ('24', 'Torola', '13', 'admin'),
    ('25', 'Yamabal', '13', 'admin'),
    ('26', 'Yoloaiquín', '13', 'admin'),
    ('01', 'Anamoros', '14', 'admin'),
    ('02', 'Bolívar', '14', 'admin'),
    ('03', 'Concepción de Oriente', '14', 'admin'),
    ('04', 'Conchagua', '14', 'admin'),
    ('05', 'El Carmen', '14', 'admin'),
    ('06', 'El Sauce', '14', 'admin'),
    ('07', 'Intipucá', '14', 'admin'),
    ('08', 'La Unión', '14', 'admin'),
    ('09', 'Lislique', '14', 'admin'),
    ('10', 'Meanguera del Golfo', '14', 'admin'),
    ('11', 'Nueva Esparta', '14', 'admin'),
    ('12', 'Pasaquina', '14', 'admin'),
    ('13', 'Polorós', '14', 'admin'),
    ('14', 'San Alejo', '14', 'admin'),
    ('15', 'San José', '14', 'admin'),
    ('16', 'Santa Rosa de Lima', '14', 'admin'),
    ('17', 'Yayantique', '14', 'admin'),
    ('18', 'Yucuaiquín', '14', 'admin');