-- This is an empty migration.
INSERT INTO specialties (name) VALUES 
('Alergología'), 
('Anestesiología'), 
('Cardiología'), 
('Cirugía cardiovascular'), 
('Cirugía general'), 
('Cirugía maxilofacial'), 
('Cirugía ortopédica'), 
('Cirugía pediátrica'), 
('Cirugía plástica'), 
('Cirugía torácica'), 
('Cirugía vascular'), 
('Dermatología'), 
('Endocrinología'), 
('Gastroenterología'), 
('Geriatría'), 
('Ginecología y obstetricia'), 
('Hematología'), 
('Hepatología'), 
('Infectología'), 
('Inmunología'), 
('Medicina de emergencias'), 
('Medicina del deporte'), 
('Medicina familiar'), 
('Medicina forense'), 
('Medicina interna'), 
('Medicina nuclear'), 
('Medicina ocupacional'), 
('Medicina paliativa'), 
('Medicina preventiva'), 
('Nefrología'), 
('Neonatología'), 
('Neumología'), 
('Neurología'), 
('Neurocirugía'), 
('Nutrición'), 
('Oftalmología'), 
('Oncología médica'), 
('Oncología radioterápica'), 
('Otorrinolaringología'), 
('Patología'), 
('Pediatría'), 
('Psiquiatría'), 
('Radiología'), 
('Reumatología'), 
('Toxicología'), 
('Traumatología'), 
('Urología'), 
('Salud pública'), 
('Psicología clínica'), 
('Genética médica'), 
('Medicina aeroespacial'), 
('Medicina del sueño'), 
('Medicina estética'), 
('Medicina hiperbárica'), 
('Medicina integrativa'), 
('Medicina del dolor'), 
('Medicina regenerativa'), 
('Adicciones'), 
('Neuropsiquiatría'), 
('Foniatría'), 
('Logopedia'), 
('Psicogeriatría'), 
('Psicología de la salud'), 
('Psicología infantil'), 
('Psicología legal y forense'), 
('Psicología neuropsicológica'), 
('Psicología organizacional'), 
('Psicología educativa'), 
('Psicología deportiva'), 
('Psicología comunitaria'), 
('Psicología de la rehabilitación'), 
('Psicología de emergencias'), 
('Psicología de la intervención en crisis'), 
('Psicología de la salud ocupacional'), 
('Psicología de la violencia'), 
('Psicología forense de menores'), 
('Psicología gerontológica'), 
('Psicología hospitalaria'), 
('Psicología jurídica'), 
('Psicología psicosomática'), 
('Psicología social'), 
('Psicología transcultural'), 
('Psicoterapia'), 
('Psicoterapia infantil y adolescente'), 
('Psicoterapia familiar y de pareja'), 
('Psicoterapia grupal'), 
('Psicoterapia humanista'), 
('Psicoterapia integradora'), 
('Psicoterapia psicoanalítica'), 
('Psicoterapia sistémica'), 
('Terapia ocupacional'), 
('Terapia física'), 
('Terapia respiratoria'), 
('Fisiatría'), 
('Neurofisiología'), 
('Proctología'), 
('Audiología'), 
('Dietética'), 
('Fitoterapia'), 
('Homeopatía');