name: 'Build and Deploy Docker Image to CapRover'

on:
  push:
    branches:
      - develop

env:
  TARGET_URL : ${{ secrets.CAPROVER_TARGET_URL }}
  TARGET_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

jobs:
  deploy:
    name: Deploy Baby Care Clinic to CapRover
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chrnorm/deployment-action@v2
        id: deployBabyCareClinic
        with:
          token: ${{ secrets.GIT_TOKEN }}
          environment-url: ${{ env.TARGET_URL }}
          environment: ${{ env.TARGET_ENV }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npx caprover deploy -h ${{ secrets.CAPROVER_HOST }} -p ${{ secrets.CAPROVER_PASSWORD }} -a ${{ secrets.CAPROVER_APP }} -b ${{ github.ref_name }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-action@v2
        with:
            token: ${{ secrets.GIT_TOKEN }}
            environment-url: ${{ env.TARGET_URL }}
            state: 'success'
            deployment_id: ${{ steps.deployBabyCareClinic.outputs.deployment_id }}

      - name: Update deployment status (failure)
        uses: chrnorm/deployment-action@v2
        if: failure()
        with:
            token: ${{ secrets.GIT_TOKEN }}
            environment-url: ${{ env.TARGET_URL }}
            state: 'failure'
            deployment_id: ${{ steps.deployBabyCareClinic.outputs.deployment_id }}
